name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run linter
        run: flake8 .

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build \
            --tag chatbot-deployer@publichealthbot-471209.iam.gserviceaccount.com/public-health-chatbot:${{ github.sha }} \
            .

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Container Registry
        run: echo ${{ secrets.CLOUD_SECRET }} \
          | docker login myregistry.example.com \
            --username ${{ secrets.CLOUD_KEY }} \
            --password-stdin

      - name: Push Docker image
        run: |
          docker push chatbot-deployer@publichealthbot-471209.iam.gserviceaccount.com/public-health-chatbot:${{ github.sha }}
